[cache]
dir = "/tmp/gs++/cache"

[grpc]
host = "0.0.0.0"
port = 50052

[bitcoind]
host = "bitcoind"
port = 18443
user = "alice"
pass = "password"
zmq_port = 28332

[utxo]
checkpoint = "./utxo-checkpoints/QmXkBQJrMKkCKNbwv4m5xtnqwU9Sq7kucPigvZW8mWxcrv"
block_height = 210
block_hash = "0000000000000000000000000000000000000000000000000000000000000000"
checkpoint_load = false
checkpoint_save = false

[zmqpub]
bind = "tcp://0.0.0.0:28339"

[graphsearch]
max_exclusion_set_size = 5
private_key = "aa43582503f91bd8103ef2b5e9ae7cd7639b47da672542d280d01bf23e410871"

[services]
graphsearch = true
graphsearch_rpc = true
zmq = true
grpc = true
utxosync = true
cache = true
zmqpub = true
