name: Deploy Unstable (from master)

on:
  push:
    branches:
      - deploy
jobs:
  deploy_unstable:
    runs-on: ubuntu-latest
    steps:
      - name: Save SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa.key
          sudo chmod 600 ~/.ssh/id_rsa.key
          ssh-keyscan rest-unstable.mainnet.cash >> ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.UNSTABLE_PRIVATE_KEY}}
      - name: Push to rest-unstable
        run: |
          pwd
          ls -la
          git branch
          git push dokku@rest-unstable.mainnet.cash origin deploy:master
        shell: bash
